Hooks:PostHook(MusicManager, "jukebox_default_tracks", "display_default_track", function(self)
    self:track_attachment_add("heist_constantine_ondisplay_nar_name", "music_fish")
	self:track_attachment_add("heist_constantine_smackdown_nar_name", "track_30")
	self:track_attachment_add("heist_constantine_smackdown2_nar_name", "track_43")
	self:track_attachment_add("heist_constantine_mobsterclub_nar_name", "track_42")
	self:track_attachment_add("heist_constantine_clubhouse_nar_name", "track_47_gen")
	self:track_attachment_add("heist_constantine_apartment_nar_name", "track_52")
	self:track_attachment_add("heist_constantine_butcher_nar_name", "track_53")	
	self:track_attachment_add("heist_constantine_mansion_nar_name", "track_66")	
	self:track_attachment_add("heist_constantine_policestation_nar_name", "track_38")		
	self:track_attachment_add("heist_constantine_gunrunnerclubhouse_nar_name", "track_54")	
	self:track_attachment_add("heist_constantine_resort_nar_name", "track_29")	
	self:track_attachment_add("heist_constantine_murkyairport_nar_name", "track_60")
	self:track_attachment_add("heist_constantine_restaurant_nar_name", "track_77")	
	self:track_attachment_add("heist_constantine_penthouse_nar_name", "track_78")
	self:track_attachment_add("heist_constantine_gold_nar_name", "track_31")
	self:track_attachment_add("heist_constantine_wintersniper_nar_name", "music_dark")
	self:track_attachment_add("heist_constantine_dwtd_nar_name", "track_18")	
	self:track_attachment_add("heist_constantine_suburbia_nar_name", "track_58")	
	self:track_attachment_add("heist_constantine_train_nar_name", "track_67")	
	self:track_attachment_add("heist_constantine_jungle_nar_name", "track_65")		
	self:track_attachment_add("heist_constantine_fiesta_nar_name", "track_69")		
	self:track_attachment_add("heist_constantine_yacht_nar_name", "track_71")	
	self:track_attachment_add("heist_constantine_cart_dwn_nar_name", "track_68")	
	self:track_attachment_add("heist_constantine_cart_con_nar_name", "track_68")		
end)